RELATIVE_PATH = 'context/ticker_scraper'
FILE_NAME_SUFFIX = '-symbols.csv'
STOCK_COLLECTIONS_PATH = f'{RELATIVE_PATH}/main/stock_collections_csv/'
TICKER_SCRAPER_TEST_PATH = f'{RELATIVE_PATH}/tests/'
WIKIPEDIA_BASE_URL = 'https://en.wikipedia.org/wiki'
TOP_FOREIGN_STOCKS_BASE_URL = 'https://topforeignstocks.com/listed-companies-lists'
